on:
  workflow_dispatch:

name: Test
jobs:
  base:
    name: base
    runs-on: ubuntu-latest
    steps:
      - run: echo Base
  middle:
    name: middle
    runs-on: ubuntu-latest
    needs:
      - base
      - base
    steps:
      - run: echo Middle
  end:
    name: end
    runs-on: ubuntu-latest
    needs:
      - middle
    steps:
      - run: echo End
